Dost/Dost/Controllers/NFCProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dost.Models;
using System.Data;
using System.Data.SqlClient;
using Newtonsoft.Json;
using System.Net;
//using System.Web.Script.Serialization;
using System.Text.RegularExpressions;
using System.IO;
using System.Drawing;
using IronBarCode;
using Dost.Filter;

namespace Dost.Controllers
{
    public class NFCProfileController : BaseController
    {
        // GET: NFCProfile
        // GET: NFC
        public ActionResult ProfileUpdate(string EncCode)
        {
            //string url = "https://dost.click/NFC/Profile?id=H8eoDq2dRNnw2LmzMaZaJQ==";
            //MyURLShortener u = new MyURLShortener();
            //string str = u.MyURLShorten(url);
            #region ddlgender
            List<SelectListItem> ddlgender = Common.BindGender();
            ViewBag.ddlgender = ddlgender;
            #endregion ddlgender
            NFCProfileModel model = new NFCProfileModel();
            //model.Code = desc;
            model.PK_UserId = Session["Pk_userId"].ToString();
            List<NFCProfileModel> lstUerProfile = new List<NFCProfileModel>();
            #region ddlEmailList
            int count = 0;
            List<SelectListItem> ddlEmail = new List<SelectListItem>();
            DataSet ds1 = model.GetmailList();
            if (ds1 != null && ds1.Tables.Count > 0 && ds1.Tables[0].Rows.Count > 0)
            {
                foreach (DataRow r in ds1.Tables[0].Rows)
                {
                    if (count == 0)
                    {
                        ddlEmail.Add(new SelectListItem { Text = "Select Email", Value = "0" });
                    }
                    ddlEmail.Add(new SelectListItem { Text = r["Content"].ToString(), Value = r["Pk_NfcProfileId"].ToString() });
                    count = count + 1;
                }
            }
            ViewBag.ddlEmail = ddlEmail;
            #endregion
            #region Mobile
            int count1 = 0;
            List<SelectListItem> Mobile = new List<SelectListItem>();
            DataSet ds2 = model.GetContactList();
            if (ds2 != null && ds2.Tables.Count > 0 && ds2.Tables[0].Rows.Count > 0)
            {
                foreach (DataRow r in ds2.Tables[0].Rows)
                {
                    if (count == 0)
                    {
                        Mobile.Add(new SelectListItem { Text = "Select Mobile No.", Value = "0" });
                    }
                    Mobile.Add(new SelectListItem { Text = r["Content"].ToString(), Value = r["Pk_NfcProfileId"].ToString() });
                    count = count + 1;
                }
            }

            ViewBag.Mobile = Mobile;
            if (EncCode != null && EncCode != "")
            {
                model.Code = EncCode;
            }
            else if (Session["NFCCode"] != null && Session["NFCCode"].ToString() != "")
            {
                model.Code = Session["NFCCode"].ToString();
            }
            else if (Session["UserNFCCode"].ToString() != "na")
            {
                model.Code = Session["UserNFCCode"].ToString();
            }
            else {
            }
            #endregion
            #region SocialMedia
            List<SelectListItem> SocialMedia = new List<SelectListItem>();
            DataSet ds3 = model.GetSocialMediaList();
            if (ds3 != null && ds3.Tables.Count > 0 && ds3.Tables[0].Rows.Count > 0)
            {
                foreach (DataRow r in ds3.Tables[0].Rows)
                {
                    if (count == 0)
                    {
                        SocialMedia.Add(new SelectListItem { Text = "Select Social Media", Value = "0" });
                    }
                    SocialMedia.Add(new SelectListItem { Text = r["Content"].ToString(), Value = r["Pk_NfcProfileId"].ToString() });
                    count = count + 1;
                }
            }
            ViewBag.SocialMedia = SocialMedia;
            #endregion SocialMedia
            #region WebLink
            List<SelectListItem> WebLink = new List<SelectListItem>();
            DataSet ds4 = model.GetWebLinkList();
            if (ds4 != null && ds4.Tables.Count > 0 && ds4.Tables[0].Rows.Count > 0)
            {
                foreach (DataRow r in ds4.Tables[0].Rows)
                {
                    if (count == 0)
                    {
                        WebLink.Add(new SelectListItem { Text = "Select Web Link", Value = "0" });
                    }
                    WebLink.Add(new SelectListItem { Text = r["Content"].ToString(), Value = r["Pk_NfcProfileId"].ToString() });
                    count = count + 1;
                }
            }
            ViewBag.WebLink = WebLink;
            #endregion WebLink
            #region ddlWhatsappList
            int count6 = 0;
            List<SelectListItem> ddlWhatsapp = new List<SelectListItem>();
            DataSet dsWh = model.GetWhatsappList();
            if (dsWh != null && dsWh.Tables.Count > 0 && dsWh.Tables[0].Rows.Count > 0)
            {
                foreach (DataRow r in dsWh.Tables[0].Rows)
                {
                    if (count6 == 0)
                    {
                        ddlWhatsapp.Add(new SelectListItem { Text = "Select Whatsapp No.", Value = "0" });
                    }
                    ddlWhatsapp.Add(new SelectListItem { Text = r["Content"].ToString(), Value = r["Pk_NfcProfileId"].ToString() });
                    count6 = count6 + 1;
                }
            }
            ViewBag.ddlWhatsapp = ddlWhatsapp;
            #endregion
            #region ddlLocationList
            int count7 = 0;
            List<SelectListItem> ddlLocation = new List<SelectListItem>();
            DataSet dsL = model.GetLocationList();
            if (dsL != null && dsL.Tables.Count > 0 && dsL.Tables[0].Rows.Count > 0)
            {
                foreach (DataRow r in dsL.Tables[0].Rows)
                {
                    if (count7 == 0)
                    {
                        ddlLocation.Add(new SelectListItem { Text = "Select Location", Value = "0" });
                    }
                    ddlLocation.Add(new SelectListItem { Text = r["Content"].ToString(), Value = r["Pk_NfcProfileId"].ToString() });
                    count7 = count7 + 1;
                }
            }
            ViewBag.ddlLocation = ddlLocation;
            #endregion
            string[] colorContact = { "#FF4C41", "#68CF29", "#51A6F5", "#eb8153", "#FFAB2D" };
            string[] colorRedirection = { "#eb8153", "#6418C3", "#FF4C90", "#68CF90", "#90A6F9", "#FFAB8D" };
            var i = 0;
            model.DecryptedCode = Crypto.DecryptNFC(EncCode);
            DataSet ds = model.GetNFCProfileData();
            if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
            {
                ViewBag.QRImage = ds.Tables[1].Rows[0]["QrImage"].ToString();
                model.IsProfileTurnedOff = Convert.ToBoolean(ds.Tables[0].Rows[0]["IsProfileTurnedOff"]);
                foreach (DataRow r in ds.Tables[0].Rows)
                {
                    NFCProfileModel obj = new NFCProfileModel();
                    obj.PK_ProfileId = r["PK_ProfileId"].ToString();
                    obj.FirstName = r["FirstName"].ToString();
                    obj.Name = r["Name"].ToString();
                    obj.LastName = r["LastName"].ToString();
                    obj.ProfilePic = r["ProfilePic"].ToString();
                    obj.Leg = r["Leg"].ToString();
                    obj.BusinessName = r["BusinessName"].ToString();
                    obj.Designation = r["Designation"].ToString();
                    obj.Description = r["Description"].ToString();
                    obj.Status = r["Status"].ToString();
                    obj.ProfileType = r["ProfileType"].ToString();

                    if (obj.Status == "Active")
                    {
                        model.PK_ProfileId = obj.PK_ProfileId;
                        ViewBag.img = obj.ProfilePic = r["ProfilePic"].ToString();

                        model.Leg = obj.Leg;
                    }
                    obj.CardImage = r["CardImage"].ToString();
                    obj.ProfileName = r["ProfileName"].ToString();
                    obj.ActiveStatus = r["IsChecked"].ToString();
                    if (obj.ProfileType == "Redirection")
                    {
                        obj.ColorCodeRedirection = colorRedirection[i];
                    }
                    else
                    {
                        obj.ColorCodeContact = colorContact[i];
                    }
                    lstUerProfile.Add(obj);
                }
                model.lst = lstUerProfile;
            }
            NFCModel objn = new NFCModel();

            objn.Code = Crypto.DecryptNFC(model.Code);
            DataSet dsProfile = objn.GetNFCProfileData();
            //if (dsProfile != null && dsProfile.Tables.Count > 0 && dsProfile.Tables[0].Rows.Count > 0)
            //{
            //    if (Convert.ToBoolean(ds1.Tables[0].Rows[0]["IsProfileTurnedOff"]) == true)
            //    {

            //    }
            //    else
            //    {
            //        model.Name = ds1.Tables[0].Rows[0]["Name"].ToString();
            //        model.Email = ds1.Tables[0].Rows[0]["PrimaryEmail"].ToString();
            //    }
            //}
            if (dsProfile != null && dsProfile.Tables.Count > 1)
            {
                if (dsProfile.Tables[0].Rows.Count > 0)
                {
                    model.enc = Common.EnryptString(dsProfile.Tables[0].Rows[0]["PK_NFCId"].ToString());
                }
                //    ViewBag.ProfilePic = dsProfile.Tables[1].Rows[0]["ProfilePic"].ToString();
                if (dsProfile.Tables[1].Rows.Count > 0)
                {

Dost/Dost/Views/NFCProfile/Analytics.cshtml
@{
    ViewBag.Title = "Analytics";
    Layout = "~/Views/Shared/UserLayout.cshtml";
}

<div class="content-body">
    <div class="container-fluid">
        <!-- Add Project -->
        <div class="modal fade" id="addProjectSidebar">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Create Project</h5>
                        <button type="button" class="close" data-dismiss="modal">
                            <span>&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form>
                            <div class="form-group">
                                <label class="text-black font-w500">Project Name</label>
                                <input type="text" class="form-control">
                            </div>
                            <div class="form-group">
                                <label class="text-black font-w500">Deadline</label>
                                <input type="date" class="form-control">
                            </div>
                            <div class="form-group">
                                <label class="text-black font-w500">Client Name</label>
                                <input type="text" class="form-control">
                            </div>
                            <div class="form-group">
                                <button type="button" class="btn btn-primary">CREATE</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="row page-titles mx-0">
            <div class="col-sm-6">
                <div class="welcome-text">
                    <h4>Hi, welcome back!</h4>
                    <span>Analytics</span>
                </div>
            </div>
            <div class="col-sm-6 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item active"><a href="javascript:void(0)">Analytics</a></li>
                </ol>
            </div>
        </div>
        <!-- row -->


        <div class="row">
            <div class="col-12">
                <div class="row">
                    <h2>Coming Soon</h2>
                    @*<div class="col-lg-6 col-sm-6">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title">Download Analysis</h4>
                            </div>
                            <div class="card-body">
                                <div id="flotBar1" class="flot-chart"></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-sm-6">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title">Gender Analysis</h4>
                            </div>
                            <div class="card-body">
                                <div id="flotBar2" class="flot-chart"></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-sm-6">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title">Link Clicks</h4>
                            </div>
                            <div class="card-body">
                                <div id="flotLine1" class="flot-chart"></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-sm-6">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title">Lead Analysis</h4>
                            </div>
                            <div class="card-body">
                                <div id="flotLine2" class="flot-chart"></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-sm-6">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title">Age Group Analysis</h4>
                            </div>
                            <div class="card-body">
                                <div id="flotLine3" class="flot-chart"></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-sm-6">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title">Geographical Analysis</h4>
                            </div>
                            <div class="card-body">
                                <div id="flotArea1" class="flot-chart"></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-sm-6">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title">Referral Analysis</h4>
                            </div>
                            <div class="card-body">
                                <div id="flotArea2" class="flot-chart"></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-sm-6">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title">Realtime Analysis</h4>
                            </div>
                            <div class="card-body">
                                <div id="flotRealtime1" class="flot-chart"></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-sm-6">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title">Realtime Chart</h4>
                            </div>
                            <div class="card-body">
                                <div id="flotRealtime2" class="flot-chart"></div>
                            </div>
                        </div>
                    </div>*@
                </div>
            </div>
        </div>
    </div>
</div>
<script src="http://cdn.jsdelivr.net/jquery.flot/0.8.4/jquery.flot.min.js"></script>
<script src="~/vendor/global/global.min.js"></script>
<script src="~/vendor/bootstrap-select/dist/js/bootstrap-select.min.js"></script>
<script src="~/vendor/chart.js/Chart.bundle.min.js"></script>
<script src="~/vendor/flot/jquery.flot.js"></script>
<script src="~/vendor/flot/jquery.flot.pie.js"></script>
<script src="~/vendor/flot/jquery.flot.resize.js"></script>
<script src="~/vendor/flot-spline/jquery.flot.spline.min.js"></script>
<script src="./js/custom.min.js"></script>

<script>
    (function ($) {
        "use strict"

        var dzChartlist = function () {
            var flotBar1 = function () {
                debugger;
                $.plot("#flotBar1", [{
                    data: [[1, 1], [2, 3], [3, 2], [4, 4], [5, 5], [6, 6], [0, 7]]
                }], {
                    series: {
                        bars: {
                            show: true,
                            lineWidth: 0,
                            fillColor: '#EB8153'
                        }
                    },
                    grid: {
                        borderWidth: 0,
                        borderColor: 'transparent'
                    },
                    yaxis: {
                        tickColor: 'transparent',
                        font: {
                            color: '#fff',
                            size: 10
                        }
                    },
                    xaxis: { ticks: [[1, "Mon"], [2, "Tue"], [3, "Wed"], [4, "Thu"], [5, "Fri"], [6, "Sat"], [7, "Sun"]] }
                });
            }
            return {
                init: function () {
                },


                load: function () {
                    flotBar1();
                    //flotBar2();
                    //flotLine1();
                    //flotLine2();
                    //flotLine3();
                    //flotArea1();
                    //flotArea2();
                    //flotLine4();
                    //flotRealtime1();
                    //flotRealtime2();
                },

                resize: function () {
                }
            }

        }();

        jQuery(window).on('load', function () {

            dzChartlist.load();
        });

        jQuery(window).on('resize', function () {
            dzChartlist.resize();
        });
    })(jQuery);
</script>

Dost/Dost/Views/NFCProfile/Generate.cshtml
@model Dost.Models.GeneratingQRCode.QRCodeModel

@{
    ViewBag.Title = "Generate QR COde";
}

<h2>Generate QRCode</h2>


@using (Html.BeginForm("Generate", "NFCProfile", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <span style="color:red; ">@ViewBag.Message </span>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.QRCodeText, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QRCodeText, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.QRCodeText, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QRCodeImagePath, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @if (Model != null && !String.IsNullOrEmpty(Model.QRCodeImagePath))
                {
                    <img src="@Url.Content(Model.QRCodeImagePath)" alt="Image" />
                }

            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Generate QR" class="btn btn-default" name="btnqr" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Read QR Code", "Read")
</div>

@section scripts{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

}

Dost/Dost/Views/NFCProfile/SetAction.cshtml
@model Dost.Models.NFCProfileModel

@{
    ViewBag.Title = "SetAction";
    Layout = "~/Views/Shared/UserLayout.cshtml";
}
@using (Html.BeginForm("SetAction", "NFCProfile", FormMethod.Post, new { @id = "form1", enctype = "multipart/form-data" }))
{
    <div class="content-body">
        <div class="container-fluid">
            <div class="row page-titles mx-0">
                <div class="col-sm-6 p-md-0">
                    <div class="welcome-text">
                        <h4>Profile</h4>
                    </div>
                </div>
                <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                    <button type="button" class="btn btn-secondary mb-2" data-toggle="modal" data-target="#exampleModalCenter">+ Create New</button>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="exampleModalCenter">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Create a new card</h5>
                    <button type="button" class="close" data-dismiss="modal">
                        <span>&times;</span>
                    </button>
                    @*<input type="hidden" id="hdfProfile" name="PK_ProfileId" value="@Model.PK_ProfileId" />*@
                </div>
                <div class="modal-body">
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label" style="white-space: nowrap;">Profile Name</label>
                        <div class="col-sm-9">
                            @Html.TextBoxFor(m => m.ProfileName, new { @class = "form-control", @placeholder = "Profile Name" })
                        </div>
                    </div>
                    <fieldset class="form-group">
                        <div class="row">
                            <label class="col-form-label col-sm-3 pt-0">Profile Type</label>
                            <div class="col-sm-9">
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" value="Contact Card" name="ProfileType" />
                                    <label class="form-check-label">
                                        Contact Card
                                    </label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" name="ProfileType" value="Redirection">
                                    <label class="form-check-label">
                                        Redirection
                                    </label>
                                </div>
                            </div>
                        </div>
                    </fieldset>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger light" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="btnProfileAdd">Create</button>
                </div>
            </div>
        </div>
    </div>
}
<script src="../vendor/jquery/jquery.min.js"></script>
<script>
    $("#btnProfileAdd").click(function () {
        debugger;
        if (window.FormData !== undefined) {
            var fileData = new FormData();
            fileData.append('Flag', 'Profile');
            fileData.append('ProfileName', $("#ProfileName").val());
            fileData.append('ProfileType', $('input[name="ProfileType"]:checked').val());
            $.ajax({
                url: '/nfc/ProfileUpdate',
                type: "POST",
                contentType: false,
                processData: false,
                data: fileData,
                success: function (data) {
                    $("#Flag").val('');
                    if (data.Result == "Success") {
                        toastr.success(data.Message, "", {
                            timeOut: 5e3,
                            closeButton: !0,
                            debug: !1,
                            newestOnTop: !0,
                            progressBar: !0,
                            positionClass: "toast-top-right",
                            preventDuplicates: !0,
                            onclick: null,
                            showDuration: "300",
                            hideDuration: "1000",
                            extendedTimeOut: "1000",
                            showEasing: "swing",
                            hideEasing: "linear",
                            showMethod: "fadeIn",
                            hideMethod: "fadeOut",
                            tapToDismiss: !1
                        })
                    }
                    else {
                        toastr.error(data.Message, "", {
                            positionClass: "toast-top-right",
                            timeOut: 5e3,
                            closeButton: !0,
                            debug: !1,
                            newestOnTop: !0,
                            progressBar: !0,
                            preventDuplicates: !0,
                            onclick: null,
                            showDuration: "300",
                            hideDuration: "1000",
                            extendedTimeOut: "1000",
                            showEasing: "swing",
                            hideEasing: "linear",
                            showMethod: "fadeIn",
                            hideMethod: "fadeOut",
                            tapToDismiss: !1
                        })
                    }
                    GetProfilePersonalData();
                    $('#exampleModalCenter').modal('hide');
                },
                error: function (err) {
                    toastr.error("Error while inserting data", "", {
                        positionClass: "toast-top-right",
                        timeOut: 5e3,
                        closeButton: !0,
                        debug: !1,
                        newestOnTop: !0,
                        progressBar: !0,
                        preventDuplicates: !0,
                        onclick: null,
                        showDuration: "300",
                        hideDuration: "1000",
                        extendedTimeOut: "1000",
                        showEasing: "swing",
                        hideEasing: "linear",
                        showMethod: "fadeIn",
                        hideMethod: "fadeOut",
                        tapToDismiss: !1
                    })
                    GetProfilePersonalData();
                    $('#exampleModalCenter').modal('hide');
                }
            });
        }
        $("#Flag").val("Profile");
    });
</script>