Dost/Dost/Controllers/NFCController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dost.Models;
using System.Data;
using System.Data.SqlClient;
using Newtonsoft.Json;
using System.Net;
using System.Web.Script.Serialization;
using System.Text.RegularExpressions;
using System.IO;
using System.Text;

namespace Dost.Controllers
{
    public class NFCController : Controller
    {
        public ActionResult Profile(string id)
        {
            var RedirectionLink = "";
            //var enc = Crypto.EncryptNFC("DIGI946211");
            NFCProfileModel objProfile = new NFCProfileModel();
            try
            {

                if (id == null || id == "")
                {
                    return RedirectToAction("Login", "Home");
                }
                else
                { 
                }

                //if (Session["LoginId"] == null)
                //{
                //    return RedirectToAction("login_new", "home");
                //}
                NFCModel obj = new NFCModel();
                //DataSet ds11 = obj.GetNFCCodes();
                //if (ds11 != null && ds11.Tables.Count > 0 && ds11.Tables[0].Rows.Count > 0)
                //{

                //    for (int i = 0; i < ds11.Tables[0].Rows.Count; i++)
                //    {
                //        obj.LoginId = ds11.Tables[0].Rows[i]["Id"].ToString();
                //        obj.Code = Crypto.EncryptNFC(ds11.Tables[0].Rows[i]["Code"].ToString());
                //        obj.UpdateNFCEncCode();
                //    }
                //}
                id = id.Replace(" ", "+");

                //var enc = Crypto.EncryptNFC(id);
                var desc = Crypto.DecryptNFC(id);
                //if (Session["LoginId"] != null)
                //{
                //    //

                //}
                //else
                //{

                //List<Wallet> lst = new List<Wallet>();
                obj.Code = desc;
                DataSet ds = obj.CheckNFCCode();
                if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
                {
                    if (ds.Tables[0].Rows[0]["IsActivated"].ToString() != "" && Convert.ToBoolean(ds.Tables[0].Rows[0]["IsActivated"].ToString()))
                    {
                        //get profile data for activated user
                        obj.Browser = HttpContext.Request.Browser.Browser;
                        obj.IP = System.Web.HttpContext.Current.Request.ServerVariables["HTTP_X_FORWARDED_FOR"];
                        if (string.IsNullOrEmpty(obj.IP))
                        {
                            obj.IP = Request.ServerVariables["REMOTE_ADDR"];
                        }
                        obj.Medium = "Web";
                        List<Location> locations = new List<Location>();
                        string APIKey = "391fd5bcd76d4745a6c883968b50a97124d416db45218ec201a58a6d049cbb9b";
                        string url = string.Format("http://api.ipinfodb.com/v3/ip-city/?key={0}&ip={1}&format=json", APIKey, obj.IP);
                        using (WebClient client = new WebClient())
                        {
                            string json = client.DownloadString(url);
                            Location location = new JavaScriptSerializer().Deserialize<Location>(json);
                            obj.ZipCode = location.ZipCode;
                            obj.Lat = location.Latitude;
                            obj.Long = location.Longitude;
                            obj.Location = location.CityName + ' ' + location.RegionName + ' ' + location.CountryName;
                            obj.Device = GetDevice();
                        }
                        DataSet ds1 = obj.GetNFCProfileData();
                        if (ds1 != null && ds1.Tables.Count > 0 && ds1.Tables[0].Rows.Count > 0)
                        {
                            if (Convert.ToBoolean(ds1.Tables[0].Rows[0]["IsProfileTurnedOff"]) == true)
                            {
                                return Redirect("https://urdost.com/");
                            }
                            else
                            {
                                DataSet ds2 = obj.InsertLog();
                                if (ds2 != null && ds2.Tables.Count > 0 && ds2.Tables[0].Rows.Count > 0)
                                {
                                    if (ds2.Tables[0].Rows[0][0].ToString() == "1")
                                    {
                                        objProfile.LogId = ds2.Tables[0].Rows[0]["LogId"].ToString();
                                    }
                                }
                                objProfile.Name = ds1.Tables[0].Rows[0]["Name"].ToString();
                                objProfile.Email = ds1.Tables[0].Rows[0]["PrimaryEmail"].ToString();
                                objProfile.DOB = ds1.Tables[0].Rows[0]["DOB"].ToString();
                                objProfile.Mobile = ds1.Tables[0].Rows[0]["Mobile"].ToString();
                                objProfile.ProfilePic = ds1.Tables[0].Rows[0]["ProfilePic"].ToString();
                                objProfile.Gender = ds1.Tables[0].Rows[0]["Sex"].ToString();
                                objProfile.PK_UserId = ds1.Tables[0].Rows[0]["PK_UserId"].ToString();
                                objProfile.Summary = ds1.Tables[0].Rows[0]["Summary"].ToString();
                                objProfile.BusinessName = ds1.Tables[0].Rows[0]["BusinessName"].ToString();
                                objProfile.Designation = ds1.Tables[0].Rows[0]["Designation"].ToString();
                                objProfile.UserCode = ds1.Tables[0].Rows[0]["UserCode"].ToString();
                                objProfile.Leg = ds1.Tables[0].Rows[0]["NFCProfileLeg"].ToString();
                                Session["SponsorId"] = ds1.Tables[0].Rows[0]["LoginId"].ToString();
                                objProfile.ProfilePic = ds1.Tables[0].Rows[0]["ProfilePic"].ToString();


                                //IpInfo ipInfo = new IpInfo();
                                //string info = new WebClient().DownloadString("https://dost.click/" + myIP);
                                //ipInfo = JsonConvert.DeserializeObject<IpInfo>(info);
                                //RegionInfo myRI1 = new RegionInfo(ipInfo.Country);
                                //ipInfo.Country = myRI1.EnglishName;
                            }
                        }
                        if (ds1 != null && ds1.Tables.Count > 0 && ds1.Tables[1].Rows.Count > 0)
                        {
                            List<NFCContent> NfcContentList = new List<NFCContent>();

                            foreach (DataRow row in ds1.Tables[1].Rows)
                            {
                                if (row["Type"].ToString() == "Email")
                                {
                                    objProfile.Email = row["Content"].ToString();
                                }
                                NfcContentList.Add(new NFCContent()
                                {
                                    Content = row["Content"].ToString(),
                                    Type = row["Type"].ToString(),
                                    IsWhatsApp = row["IsWhatsapp"].ToString(),
                                    IsPrimary = row["IsPrimary"].ToString(),
                                    IsDisplay = Convert.ToBoolean(row["Display"])
                                });
                            }

                            if (ds1 != null && ds1.Tables.Count > 0 && ds1.Tables[2].Rows.Count > 0)
                            {
                                if (ds1.Tables[2].Rows[0]["IsRedirect"].ToString() == "True")
                                {
                                    RedirectionLink = ds1.Tables[2].Rows[0]["Content"].ToString();
                                }
                            }
                            objProfile.NfcContentList = NfcContentList;
                        }
                        if (ds1 != null && ds1.Tables.Count > 0 && ds1.Tables[3].Rows.Count > 0)
                        {
                            List<UserSkill> lstSkill = new List<UserSkill>();

                            foreach (DataRow row in ds1.Tables[3].Rows)
                            {
                                UserSkill objSkill = new UserSkill();
                                objSkill.Pk_SkillId = row["PK_SkillId"].ToString();
                                objSkill.Skill = row["Skill"].ToString();
                                lstSkill.Add(objSkill);
                            }
                            objProfile.lstSkill = lstSkill;
                        }
                        if (ds1 != null && ds1.Tables.Count > 0 && ds1.Tables[4].Rows.Count > 0)
                        {
                            List<UserLanguage> lstLanguage = new List<UserLanguage>();

                            foreach (DataRow row in ds1.Tables[4].Rows)
                            {
                                UserLanguage objLanguage = new UserLanguage();
                                objLanguage.Pk_LanguageId = row["PK_LanguageId"].ToString();
                                objLanguage.Language = row["Language"].ToString();
                                lstLanguage.Add(objLanguage);
                            }
                            objProfile.lstLanguage = lstLanguage;
                        }
                        if (ds1 != null && ds1.Tables.Count > 0 && ds1.Tables[5].Rows.Count > 0)
                        {
                            List<UserAchievement> lstAchievement = new List<UserAchievement>();

                            foreach (DataRow row in ds1.Tables[5].Rows)
                            {

Dost/Dost/Views/NFC/SetAction.cshtml
@model Dost.Models.NFCProfileModel

@{
    ViewBag.Title = "SetAction";
    Layout = "~/Views/Shared/UserLayout.cshtml";
}
@using (Html.BeginForm("SetAction", "NFC", FormMethod.Post, new { @id = "form1", enctype = "multipart/form-data" }))
{
    <div class="content-body">
        <div class="container-fluid">
            <div class="row page-titles mx-0">
                <div class="col-sm-6 p-md-0">
                    <div class="welcome-text">
                        <h4>Profile</h4>
                    </div>
                </div>
                <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                    <button type="button" class="btn btn-secondary mb-2" data-toggle="modal" data-target="#exampleModalCenter">+ Create New</button>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="exampleModalCenter">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Create a new card</h5>
                    <button type="button" class="close" data-dismiss="modal">
                        <span>&times;</span>
                    </button>
                    @*<input type="hidden" id="hdfProfile" name="PK_ProfileId" value="@Model.PK_ProfileId" />*@
                </div>
                <div class="modal-body">
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label" style="white-space: nowrap;">Profile Name</label>
                        <div class="col-sm-9">
                            @Html.TextBoxFor(m => m.ProfileName, new { @class = "form-control", @placeholder = "Profile Name" })
                        </div>
                    </div>
                    <fieldset class="form-group">
                        <div class="row">
                            <label class="col-form-label col-sm-3 pt-0">Profile Type</label>
                            <div class="col-sm-9">
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" value="Contact Card" name="ProfileType" />
                                    <label class="form-check-label">
                                        Contact Card
                                    </label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" name="ProfileType" value="Redirection">
                                    <label class="form-check-label">
                                        Redirection
                                    </label>
                                </div>
                            </div>
                        </div>
                    </fieldset>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger light" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="btnProfileAdd">Create</button>
                </div>
            </div>
        </div>
    </div>
}
<script src="../vendor/jquery/jquery.min.js"></script>
<script>
    $("#btnProfileAdd").click(function () {
        debugger;
        if (window.FormData !== undefined) {
            var fileData = new FormData();
            fileData.append('Flag', 'Profile');
            fileData.append('ProfileName', $("#ProfileName").val());
            fileData.append('ProfileType', $('input[name="ProfileType"]:checked').val());
            $.ajax({
                url: '/nfc/ProfileUpdate',
                type: "POST",
                contentType: false,
                processData: false,
                data: fileData,
                success: function (data) {
                    $("#Flag").val('');
                    if (data.Result == "Success") {
                        toastr.success(data.Message, "", {
                            timeOut: 5e3,
                            closeButton: !0,
                            debug: !1,
                            newestOnTop: !0,
                            progressBar: !0,
                            positionClass: "toast-top-right",
                            preventDuplicates: !0,
                            onclick: null,
                            showDuration: "300",
                            hideDuration: "1000",
                            extendedTimeOut: "1000",
                            showEasing: "swing",
                            hideEasing: "linear",
                            showMethod: "fadeIn",
                            hideMethod: "fadeOut",
                            tapToDismiss: !1
                        })
                    }
                    else {
                        toastr.error(data.Message, "", {
                            positionClass: "toast-top-right",
                            timeOut: 5e3,
                            closeButton: !0,
                            debug: !1,
                            newestOnTop: !0,
                            progressBar: !0,
                            preventDuplicates: !0,
                            onclick: null,
                            showDuration: "300",
                            hideDuration: "1000",
                            extendedTimeOut: "1000",
                            showEasing: "swing",
                            hideEasing: "linear",
                            showMethod: "fadeIn",
                            hideMethod: "fadeOut",
                            tapToDismiss: !1
                        })
                    }
                    GetProfilePersonalData();
                    $('#exampleModalCenter').modal('hide');
                },
                error: function (err) {
                    toastr.error("Error while inserting data", "", {
                        positionClass: "toast-top-right",
                        timeOut: 5e3,
                        closeButton: !0,
                        debug: !1,
                        newestOnTop: !0,
                        progressBar: !0,
                        preventDuplicates: !0,
                        onclick: null,
                        showDuration: "300",
                        hideDuration: "1000",
                        extendedTimeOut: "1000",
                        showEasing: "swing",
                        hideEasing: "linear",
                        showMethod: "fadeIn",
                        hideMethod: "fadeOut",
                        tapToDismiss: !1
                    })
                    GetProfilePersonalData();
                    $('#exampleModalCenter').modal('hide');
                }
            });
        }
        $("#Flag").val("Profile");
    });
</script>

Dost/Dost/Views/NFC/SetActionDashboard.cshtml
@model Dost.Models.Master
@{
    ViewBag.Title = "SetActionDashboard";
    Layout = "~/Views/Shared/UserLayout.cshtml";
}

<div class="content-body">
    <div class="container-fluid">
        <!-- Add Project -->
        <div class="modal fade" id="addProjectSidebar">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Create Project</h5>
                        <button type="button" class="close" data-dismiss="modal">
                            <span>&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form>
                            <div class="form-group">
                                <label class="text-black font-w500">Project Name</label>
                                <input type="text" class="form-control">
                            </div>
                            <div class="form-group">
                                <label class="text-black font-w500">Deadline</label>
                                <input type="date" class="form-control">
                            </div>
                            <div class="form-group">
                                <label class="text-black font-w500">Client Name</label>
                                <input type="text" class="form-control">
                            </div>
                            <div class="form-group">
                                <button type="button" class="btn btn-primary">CREATE</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="row page-titles mx-0">
            <div class="col-sm-6 p-md-0">
                <div class="welcome-text">
                    <h4>Hi, welcome back!</h4>
                    <span>Statistics</span>
                </div>
            </div>
            <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="javascript:void(0)">Widget</a></li>
                    <li class="breadcrumb-item active"><a href="javascript:void(0)">Statistics</a></li>
                </ol>
            </div>
        </div>
        <!-- row -->
        <div class="row">
            @if (Model != null)
            {
                if (Model.lst != null)
                {
                    foreach (var Item in Model.lst)
                    {
                        <div class="col-xl-3 col-xxl-4 col-lg-6 col-sm-6">
                            <div class="widget-stat card" style="background-color:@Item.Color">
                                <div class="card-body  p-4">
                                    <div class="media">
                                        <span class="mr-3">
                                            <i class="fa fa-credit-card-alt"></i>
                                        </span>
                                        <div class="media-body text-white text-right">
                                            <p class="mb-1"><a href="/NFC/ProfileUpdate" class="text-white text-activate">Edit</a></p>
                                            <h4 class="text-white">@Item.Service</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                }
            }
        </div>
    </div>
</div>